# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94142b037f3d7d1e5e4013e8c902542cb3287561014ff97f61a425d109598a6864e0a73c1d5b637cf9a01e5a958cac087051a0b2b376d5bea34adc1fd4439c6b

test:
  secret_key_base: 655c36476a89825e9818ff699be3e160e4761d7daeeb3fdead91e3a90a2c72c7586b2c0f7429624f29d00bde0032893c7ad1691d781140d1521aa3ce2f654243

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
